services:
  n8n:
    image: docker.n8n.io/n8nio/n8n
    container_name: n8n
    restart: always
    ports:
      - "127.0.0.1:5678:5678"
    labels:
      - traefik.enable=true
      - traefik.http.routers.n8n.rule=Host(`localhost`)
      - traefik.http.routers.n8n.tls=true
      - traefik.http.routers.n8n.entrypoints=web,websecure
      - traefik.http.routers.n8n.tls.certresolver=mytlschallenge
    environment:
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - WEBHOOK_URL=https://localhost/
      - GENERIC_TIMEZONE=America/Argentina/Buenos_Aires
      - QUEUE_MODE=redis
      - REDIS_HOST=redis-n8n
      - REDIS_PORT=6379
    volumes:
      - ./n8n_data:/home/node/.n8n
      - ./local-files:/files
    networks:
      - evolution-network

  postgres-n8n:
    image: postgres:14
    container_name: postgres-n8n
    environment:
      - POSTGRES_DB=nochon
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=n8n
    volumes:
      - ./database/n8n/postgres:/var/lib/postgresql/data
    networks: 
      - evolution-network

  redis-n8n:
    image: redis:alpine
    container_name: redis-n8n
    command: [ "redis-server", "--appendonly", "yes", "--port", "6379" ]
    volumes:
      - ./database/n8n/redis:/data
    networks: 
      - evolution-network
